added textbox generator
supreethavadhani/metadev-client-example pull request #1
Opened 2022-06-28 05:51 UTC by supreethavadhani

## Add a textbox generator

The commit consists of rendering all the textboxes in the form using a single line of html.

### Ticket - [LAB-176](https://oregonstate-innovationlab.atlassian.net/browse/LAB-176)

### Before
![Screen Shot 2022-06-27 at 8 49 53 PM](https://user-images.githubusercontent.com/23350798/176102887-66b46a4b-9378-48b9-ab64-454f3e8afc4c.png)

### After
![Screen Shot 2022-06-27 at 10 46 12 PM](https://user-images.githubusercontent.com/23350798/176102923-711694a1-151c-44cb-8ac3-4fc9d17be79e.png)

## What you need to check for

![Screen Shot 2022-06-27 at 10 46 36 PM](https://user-images.githubusercontent.com/23350798/176103097-49c3fe82-12fe-4216-a594-375a4c1b2962.png)

1. The application runs on localhost 
2. The field validations work

2022-06-28 23:01 UTC, wbraynen commented on src/app/framework-modules/elements/ct-field-generator/component.ts
> +import {FormBuilder, FormGroup, Validators, FormControl} from '@angular/forms';
Formatting nitpick.  You have a space after `{` and a space before `}` on the neighboring lines, but not here.  Reformat/lint this line for consistency?

2022-06-28 23:02 UTC, wbraynen commented on src/app/framework-modules/elements/ct-field-generator/component.ts
> +export class CTFieldGen {
Would it make sense to add a javadoc here to explain what this does?  Also, what does the "CT" prefix mean in "CTFieldGen"?  Finally, what is "Gen"?  Generator?  Maybe write it out in full, so it's more self documenting?

2022-06-28 23:05 UTC, wbraynen commented on src/app/framework-modules/elements/elements.ts
>    export class ElementsModule {
I thought you had a linter installed?  If you do and your linter catches these things, but you forgot to run this new code through the linter, then I would highly recommend installing a linter as part of your PR checks.  Your linter could do one of the following:
Option 1. The linter lints and reformats the code up on the CI server and recommits it somehow. This is the more aggressive option.
Option 2. The linter lints (up on the CI server) and if the git repo is dirty after that (that is, the linter has made any changes), then your PR check fails. This is the more common conservative option.

2022-06-28 23:06 UTC, wbraynen requested changes
A few small nitpicky comments to address. Maybe time to create a PR check, at least for linting (if not to run unit tests)?  Also, would it make sense to have unit tests for this code?  Is it possible?

2022-06-28 23:12 UTC, wbraynen commented
One other thing, though too late for this PR: as a work habit, you could prefix your branch name with the ticket number.  It then makes it easier to write the PR comments since to remember the ticket number all you have to do is look at your branch name. For example, `LAB-176-textbox-gen` instead of `textbox-gen`.  Also, FYI: snake case is easier to read than hyphens—studies show faster reading speed.

2022-06-30 02:37 UTC, osu-mp commented
My feedback is not for this PR per se, but for the general project: what is meta-dev? I'm jumping in without the background that others may have, but it's not clear what the overall goal of the project is. The README has useful info on how to install/run the project, but a few sentences about what the project does/is for would be helpful.

2022-06-30 05:03 UTC, supreethavadhani commented
@osu-mp created a new issue [Issue 2](https://github.com/supreethavadhani/metadev-client-example/issues/2)

2022-07-01 04:55 UTC, gangamamulya commented on src/app/framework-modules/elements/ct-field-generator/component.ts
> +
There are many extra spaces, may be linting should be done to code.

2022-07-01 05:15 UTC, gangamamulya reviewed
Overall, the changes made seems to be very useful with the use of  ct-field-generator. And may be you can make it more self documenting and also add linting to format your code and remove extra spaces.

2022-07-01 05:55 UTC, wbraynen commented
@supreethavadhani It looks like you're now using a mix of GitHub's issue track and Jira.  For example, this is not Jira: https://github.com/supreethavadhani/metadev-client-example/issues/2  Wouldn't using two different issue tracking platforms get confusing?

2022-07-05 01:12 UTC, wbraynen requested changes
What is a textbox generator?

The PR description is a little cryptic.  Maybe something like this instead, plus an explanation of what the last screenshot illustrates?

Plus, either inline, some link to some context about what this is still?

![image](https://user-images.githubusercontent.com/4765449/177230786-d1fa9768-97ca-4c32-9b35-732fbba5a27f.png)

2022-07-06 02:51 UTC, supreethavadhani commented
> Overall, the changes made seems to be very useful with the use of ct-field-generator. And may be you can make it more self documenting and also add linting to format your code and remove extra spaces.

@gangamamulya I fixed the liniting issue. 
RE self documenting code - Im not able to figure out where I missed out on implementing self documenting code. 🤔  Am I missing something 👀  ! If you can help me find out where exactly I missed it I'll fix it and push a new commit 👍

2022-07-06 03:10 UTC, supreethavadhani commented
> What is a textbox generator?
> 
> The PR description is a little cryptic. Maybe something like the following (see my screenshot below), plus an explanation of what the last screenshot illustrates?
> 
> Plus, either inline, some link to some context about what this is still?
> 
> ![image](https://user-images.githubusercontent.com/4765449/177230786-d1fa9768-97ca-4c32-9b35-732fbba5a27f.png)

Does this version look better?

2022-07-07 02:28 UTC, osu-mp commented
Linter results look better. The other feedback I'd offer is seconding the suggestion for self-documenting code. Within the code, it's not obvious what field-generator does/why it reduces several lines into one.

2022-07-07 02:46 UTC, wbraynen requested changes
Please make more self-documenting.  For examples of what that means, see the comments I left on https://github.com/supreethavadhani/metadev-client-example/pull/3

2022-07-07 17:07 UTC, merged

2022-07-07 17:41 UTC, supreethavadhani commented
The PR had a ton of file changes.
Reviewed code with @wbraynen in person.
Forced the merge because of the the 180,000 lines change.